{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "clopus-watcher.serviceAccountName" . }}
  labels:
    {{- include "clopus-watcher.labels" . | nindent 4 }}
{{- end }}
